name: Clang Format

on:
  push:
  pull_request:

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache custom apt package cache
        uses: actions/cache@v3
        with:
          path: ./apt-cache
          key: apt-cache-${{ runner.os }}-v1
          restore-keys: |
            apt-cache-${{ runner.os }}-v1


      - name: Download clang-format
        run: |
          sudo apt-get update
          mkdir -p ./apt-cache
          sudo apt-get -o dir::cache::archives="$(pwd)/apt-cache" \
          --download-only install clang-format

          - name: Install packages
          run: |
          sudo dpkg -i apt-cache/*.deb || true
          sudo apt-get install -o dir::cache::archives="$(pwd)/apt-cache" -f -y

      - name: Format code
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)$' -exec clang-format -style=file -i {} \;
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: format code with clang-format" && git push) 